
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: emulator-app
        honor_labels: true
        scrape_interval: 1m
        scrape_timeout: 30s
        metrics_path: /api/metrics
        scheme: http
        static_configs:
          - targets:
              -  danemulator.ddns.net 
grafana:
  enabled: true
  persistence:
    enabled: true
    type: sts
    storageClassName: "gp2-mongo"
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection

crds:
  enabled: true