apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  aws_access_key_id: QUtJQVlYV0JPREJQRFYzR0dJVTQ=
  aws_secret_access_key: dzltc2xoZ1YrMCtPRmZKRFFqZlhBN3IvNTdXbGExQ2FvYkJDWVM3cA==
  aws_s3_bucket: ZGFuLXRlcnJhZm9ybS1zMw==