apiVersion: v2
name: emulator-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"


dependencies:
  - name: mongodb
    version: "16.4.0"  
    repository: "https://charts.bitnami.com/bitnami"
