apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: emulator-monitor
  namespace: myapp
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - emulator
  endpoints:
    - port: http  
      path: /api/metrics
      interval: 30s
      scrapeTimeout: 10s